### ISSUE TITLE
Can't list nor download product(s)

### ISSUE THREAD

**Issue by mickaelistria** [eclipselabs/language-servers-for-eclipse#4]
I'm trying to download the RCP product but the provided URL doesn't list the content of the repo, and accessing directly file ( https://dl.bintray.com/mniewrzal/language-servers-for-eclipse/products/lsp.ide-linux.gtk.x86_64.zip ) asks for credentials.

**Comment by mniewrzal** [comment]
Can you try now?

**Comment by mickaelistria** [comment]
I can see the list of files and download them. Thanks.

**Comment by mniewrzal** [comment]
I need to fix script for Bintray upload. Files can be unavailable from time to time today.
